version: '3.4'
services: 
  postgress:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
      network: host 
    ports:
      - '3050:80'
  api:
    depends_on: 
      - postgress
    build:
      dockerfile: Dockerfile.dev
      context: ./server
      network: host
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
      network: host
    volumes: 
      - /app/node_modules
      - ./client:/app
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: 
        dockerfile: Dockerfile.dev
        context: ./worker
        network: host
    volumes: 
      - /app/node_modules
      - ./worker:/app

      